import type { Metadata } from 'next';
import './globals.css';
import { Inter as FontSans, Roboto } from 'next/font/google';
import localFont from 'next/font/local';
import { cn } from '@/lib/utils';
import Link from 'next/link';

const fontSans = FontSans({
    subsets: ['latin'],
    variable: '--font-sans',
});

const fontRoboto = Roboto({ subsets: ['vietnamese'], weight: ['100', '500'] });

const myFont = localFont({
    src: './RobotoFlex-Regular.ttf',
    display: 'swap',
    variable: '--font-roboto-flex',
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                // className={cn(
                //     'min-h-screen bg-background font-sans antialiased',
                //     fontSans.variable,
                // )}
                // className={fontRoboto.className}
                // className={`${myFont.className}`}
                className={`${myFont.variable}`}
            >
                <ul>
                    <li>
                        <Link href="/blog">Blog Page</Link>
                    </li>
                    <li>
                        <Link href="/login">Login Page</Link>
                    </li>
                    <li>
                        <Link href="/register">Register Page</Link>
                    </li>
                </ul>
                
                {children}
            </body>
        </html>
    );
}
